language: node_js
node_js:
  - '8'
  - '6'
notifications:
  email: false
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
after_script:
  - npm run report-coverage
branches:
  only:
    - master
    - /^greenkeeper/.*$/
