language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '8'
  - '6'
notifications:
  email: false
script:
  - npm run test:prod && npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
